import { createSlice, PayloadAction } from '@reduxjs/toolkit';

interface SignupConstraintsSliceState {
  USERNAME_INPUT_CLICKED: boolean;    
  EMAIL_INPUT_CLICKED: boolean;
  PASSWORD_INPUT_CLICKED: boolean;
  AGE_INPUT_CLICKED: boolean;
  USER_EMAIL_EXTENSION: string;

  USERNAME_OVER_OR_8: boolean;
  USERNAME_UNDER_OR_20: boolean;
  USERNAME_FAILS_UNIQUE: boolean;
  USERNAME_FAILS_NO_CURSES: boolean;

  EMAIL_EXTENSION: string;
  EMAIL_HAS_AT_CHAR: boolean;
  EMAIL_HAS_EXTENSION: boolean;
  EMAIL_FAILS_UNIQUE: boolean;

  PASSWORD_HAS_CAPS: boolean;
  PASSWORD_HAS_NUMS: boolean;
  PASSWORD_HAS_SPECIAL: boolean;  

  PASSWORD_FAILS_TOO_EZ: boolean;
  PASSWORD_FAILS_NO_CURSES: boolean;

  AGE_FAILS_TOO_YOUNG: boolean;

  INPUTS_CLICKED_YET: boolean;

}

const initialState: SignupConstraintsSliceState = {    
  USERNAME_INPUT_CLICKED: false,
  EMAIL_INPUT_CLICKED: false,
  PASSWORD_INPUT_CLICKED: false,
  AGE_INPUT_CLICKED: false,
  USER_EMAIL_EXTENSION: '',

  USERNAME_OVER_OR_8: false,
  USERNAME_UNDER_OR_20: false,
  USERNAME_FAILS_UNIQUE: false,
  USERNAME_FAILS_NO_CURSES: false,

  EMAIL_EXTENSION: '',
  EMAIL_HAS_AT_CHAR: false,
  EMAIL_HAS_EXTENSION: false,
  EMAIL_FAILS_UNIQUE: false,

  PASSWORD_HAS_CAPS: false,
  PASSWORD_HAS_NUMS: false,
  PASSWORD_HAS_SPECIAL: false,

  PASSWORD_FAILS_TOO_EZ: false,
  PASSWORD_FAILS_NO_CURSES: false,

  AGE_FAILS_TOO_YOUNG: false,

  INPUTS_CLICKED_YET: false,

};

                                        
const signupConstraintsSlice = createSlice({
  name: 'signupConstraints',
  initialState,
  reducers: { 
    TOGGLE_USERNAME_INPUT_CLICKED: (state) => { state.USERNAME_INPUT_CLICKED = !state.USERNAME_INPUT_CLICKED },
    TOGGLE_EMAIL_INPUT_CLICKED: (state) => { state.EMAIL_INPUT_CLICKED = !state.EMAIL_INPUT_CLICKED },
    TOGGLE_PASSWORD_INPUT_CLICKED: (state) => { state.PASSWORD_INPUT_CLICKED = !state.PASSWORD_INPUT_CLICKED },
    TOGGLE_AGE_INPUT_CLICKED: (state) => { state.AGE_INPUT_CLICKED = !state.AGE_INPUT_CLICKED },

    SET_USER_EMAIL_EXTENSION: (state, action) => { state.USER_EMAIL_EXTENSION = action.payload },
    TOGGLE_USERNAME_OVER_OR_8: (state) => { state.USERNAME_OVER_OR_8 = !state.USERNAME_OVER_OR_8 },  
    TOGGLE_USERNAME_UNDER_OR_20: (state) => { state.USERNAME_UNDER_OR_20 = !state.USERNAME_UNDER_OR_20 },  
    TOGGLE_USERNAME_FAILS_UNIQUE: (state) => { state.USERNAME_FAILS_UNIQUE = !state.USERNAME_FAILS_UNIQUE },  
    TOGGLE_USERNAME_FAILS_NO_CURSES: (state) => { state.USERNAME_FAILS_NO_CURSES = !state.USERNAME_FAILS_NO_CURSES },  

    SET_EMAIL_EXTENSION: (state, action) => { state.EMAIL_EXTENSION = action.payload },  
    TOGGLE_EMAIL_HAS_AT_CHAR: (state) => { state.EMAIL_HAS_AT_CHAR = !state.EMAIL_HAS_AT_CHAR },  
    TOGGLE_EMAIL_HAS_EXTENSION: (state) => { state.EMAIL_HAS_EXTENSION = !state.EMAIL_HAS_EXTENSION },  
    TOGGLE_EMAIL_FAILS_UNIQUE: (state) => { state.EMAIL_FAILS_UNIQUE = !state.EMAIL_FAILS_UNIQUE },  

    TOGGLE_PASSWORD_HAS_CAPS: (state) => { state.PASSWORD_HAS_CAPS = !state.PASSWORD_HAS_CAPS },  
    TOGGLE_PASSWORD_HAS_NUMS: (state) => { state.PASSWORD_HAS_NUMS = !state.PASSWORD_HAS_NUMS },  
    TOGGLE_PASSWORD_HAS_SPECIAL: (state) => { state.PASSWORD_HAS_SPECIAL = !state.PASSWORD_HAS_SPECIAL },  
    TOGGLE_PASSWORD_FAILS_TOO_EZ: (state) => { state.PASSWORD_FAILS_TOO_EZ = !state.PASSWORD_FAILS_TOO_EZ },  
    TOGGLE_PASSWORD_FAILS_NO_CURSES: (state) => { state.PASSWORD_FAILS_NO_CURSES = !state.PASSWORD_FAILS_NO_CURSES }, 
    TOGGLE_AGE_FAILS_TOO_YOUNG: (state) => { state.AGE_FAILS_TOO_YOUNG = !state.AGE_FAILS_TOO_YOUNG },

    TOGGLE_INPUTS_CLICKED_YET: (state) => { state.INPUTS_CLICKED_YET = !state.INPUTS_CLICKED_YET },  
  },
});

export const 
{ 
    TOGGLE_USERNAME_INPUT_CLICKED, TOGGLE_EMAIL_INPUT_CLICKED, TOGGLE_PASSWORD_INPUT_CLICKED, TOGGLE_AGE_INPUT_CLICKED,
    TOGGLE_USERNAME_OVER_OR_8, TOGGLE_USERNAME_UNDER_OR_20, TOGGLE_USERNAME_FAILS_UNIQUE, TOGGLE_USERNAME_FAILS_NO_CURSES,

    SET_EMAIL_EXTENSION, TOGGLE_EMAIL_HAS_AT_CHAR, TOGGLE_EMAIL_HAS_EXTENSION, TOGGLE_EMAIL_FAILS_UNIQUE, 
    TOGGLE_PASSWORD_HAS_CAPS, TOGGLE_PASSWORD_HAS_NUMS, TOGGLE_PASSWORD_HAS_SPECIAL,

    TOGGLE_PASSWORD_FAILS_TOO_EZ, TOGGLE_PASSWORD_FAILS_NO_CURSES,
    TOGGLE_AGE_FAILS_TOO_YOUNG,

    TOGGLE_INPUTS_CLICKED_YET
} = signupConstraintsSlice.actions;

export default signupConstraintsSlice.reducer;
export type SignupConstraintsState = SignupConstraintsSliceState;
