import {
    SET_CURR_DAY, 
    TOGGLE_ARE_WE_FRIENDS,
    SET_CURR_DAY_MOMENT, SET_CURR_DAY_THOUGHTS, SET_CURR_DAY_FIELDS, UPDATE_FIELDS_CHECKBOX, SET_CURR_DAY_GREATFULL,
    SET_CURR_DAY_COMMENTS, TOGGLE_CURR_DAY_IS_3_WORDS,
    TOGGLE_ALL_PHOTOS_SEEN, TOGGLE_ALL_COMMENTS_SEEN,

    SET_CURR_DAY_SELECTION, SET_PREVIOUS_DAY_SELECTION, SET_CURR_DAY_USER_PROFILE_IMG,
    
    TOGGLE_CURR_DAY_HAS_THOUGHTS, TOGGLE_CURR_DAY_HAS_MOMENTS, TOGGLE_CURR_DAY_HAS_FIELDS, TOGGLE_CURR_DAY_HAS_GREATFULL,
    TOGGLE_CURR_DAY_HAS_MEDIA, TOGGLE_CURR_DAY_HAS_LOCK, SET_CURR_DAY_USERS_PASS_LOCKS, TOGGLE_DOES_CURR_USER_PASS_LOCK,
    SET_CURR_DAY_USERS_CAN_TRASH,
    TOGGLE_CURR_DAY_HAS_BALLOT, SET_CURR_DAY_USER_PRIVACY, 
    SET_DO_WE_FOLLOW_EACH_OTHER, SET_DO_WE_BLOCK_EACH_OTHER, SET_CURR_DAY_NON_ANONYMOUS_TO_ME,
    
    SET_BOTTOM_BAR_SELECTION,
    SET_THOUGHTS_BIN, INCREMENT_THOUGHTS_BIN_INDEX, DECREMENT_THOUGHTS_BIN_INDEX, DETERMINE_THOUGHTS_BIN_INDEX,
    
    SET_CAPTIONS_BIN, INCREMENT_CAPTIONS_BIN_INDEX, DECREMENT_CAPTIONS_BIN_INDEX, DETERMINE_CAPTIONS_BIN_INDEX,
    SET_PHOTOS_BIN, INCREMENT_PHOTOS_BIN_INDEX, DECREMENT_PHOTOS_BIN_INDEX, DETERMINE_PHOTOS_BIN_INDEX,
    TOGGLE_CURR_DAY_IS_CHECKED,
    SET_MOMENTS_BIN, INCREMENT_MOMENTS_BIN_INDEX, DECREMENT_MOMENTS_BIN_INDEX, DETERMINE_MOMENTS_BIN_INDEX,
    
    TOGGLE_FIELDS_CONSTANTSEE_CLICK, SET_FIELDS_CONSTANTSEE_TEXT, SET_FIELDS_CONSTANTSEE_INDEX,
    
    SET_GREATFULL_ZOOM_IN_OUT_CLICK,

    // COMMENTING state:
    SET_CURR_DAY_COMMENTING_USERS_PROFILE_ICON_BIN, SET_CURR_DAY_COMMMENTING_USERS_SHOW_CHILD_COMMENTS_BIN, 
    SET_CURR_DAY_CURR_PARENT_THOUGHT, 

    // TOGGLE_CURR_DAY_STAR_IS_CLICKED, SET_CURR_DAY_STAR_CLICKED_INDEX,
    
    TOGGLE_CURR_DAY_QUESTION_IS_CLICKED,
    SET_CURR_DAY_COMMENTING_STARS_QUESTION_CLICK_BIN
} from "./daySlice" // learn smth new everyday 

export {
    SET_CURR_DAY, 
    TOGGLE_ARE_WE_FRIENDS,
    SET_CURR_DAY_MOMENT, SET_CURR_DAY_THOUGHTS, SET_CURR_DAY_FIELDS, UPDATE_FIELDS_CHECKBOX, SET_CURR_DAY_GREATFULL,
    SET_CURR_DAY_COMMENTS, TOGGLE_CURR_DAY_IS_3_WORDS,
    TOGGLE_ALL_PHOTOS_SEEN, TOGGLE_ALL_COMMENTS_SEEN,

    SET_CURR_DAY_SELECTION, SET_PREVIOUS_DAY_SELECTION, SET_CURR_DAY_USER_PROFILE_IMG,
    
    TOGGLE_CURR_DAY_HAS_THOUGHTS, TOGGLE_CURR_DAY_HAS_MOMENTS, TOGGLE_CURR_DAY_HAS_FIELDS, TOGGLE_CURR_DAY_HAS_GREATFULL,
    TOGGLE_CURR_DAY_HAS_MEDIA, TOGGLE_CURR_DAY_HAS_LOCK, SET_CURR_DAY_USERS_PASS_LOCKS, TOGGLE_DOES_CURR_USER_PASS_LOCK,
    SET_CURR_DAY_USERS_CAN_TRASH,
    TOGGLE_CURR_DAY_HAS_BALLOT, SET_CURR_DAY_USER_PRIVACY, 
    SET_DO_WE_FOLLOW_EACH_OTHER, SET_DO_WE_BLOCK_EACH_OTHER, SET_CURR_DAY_NON_ANONYMOUS_TO_ME,
    
    SET_BOTTOM_BAR_SELECTION,
    SET_THOUGHTS_BIN, INCREMENT_THOUGHTS_BIN_INDEX, DECREMENT_THOUGHTS_BIN_INDEX, DETERMINE_THOUGHTS_BIN_INDEX,
    
    SET_CAPTIONS_BIN, INCREMENT_CAPTIONS_BIN_INDEX, DECREMENT_CAPTIONS_BIN_INDEX, DETERMINE_CAPTIONS_BIN_INDEX,
    SET_PHOTOS_BIN, INCREMENT_PHOTOS_BIN_INDEX, DECREMENT_PHOTOS_BIN_INDEX, DETERMINE_PHOTOS_BIN_INDEX,
    TOGGLE_CURR_DAY_IS_CHECKED,
    SET_MOMENTS_BIN, INCREMENT_MOMENTS_BIN_INDEX, DECREMENT_MOMENTS_BIN_INDEX, DETERMINE_MOMENTS_BIN_INDEX,
    
    TOGGLE_FIELDS_CONSTANTSEE_CLICK, SET_FIELDS_CONSTANTSEE_TEXT, SET_FIELDS_CONSTANTSEE_INDEX,
    
    SET_GREATFULL_ZOOM_IN_OUT_CLICK,

    // COMMENTING state:
    SET_CURR_DAY_COMMENTING_USERS_PROFILE_ICON_BIN, SET_CURR_DAY_COMMMENTING_USERS_SHOW_CHILD_COMMENTS_BIN, 
    SET_CURR_DAY_CURR_PARENT_THOUGHT, 

    // TOGGLE_CURR_DAY_STAR_IS_CLICKED, SET_CURR_DAY_STAR_CLICKED_INDEX,
    
    TOGGLE_CURR_DAY_QUESTION_IS_CLICKED,
    SET_CURR_DAY_COMMENTING_STARS_QUESTION_CLICK_BIN
